require "cucumber"
require "http"
require "rspec"
require "securerandom"
require "selenium-webdriver"

require_relative "../../command_center"
require_relative "../../login_page"
require_relative "../../lib/authorization"
require_relative "../../lib/devices/manager"
require_relative "../../lib/locations"
require_relative "../../lib/locations/location"
require_relative "../../lib/locations/location_manager"
require_relative "../../uitest"
require_relative "../../lib/pages/myteampage"
require_relative "../../lib/api/user_manager"
