require "cucumber"
require "http"
require "rspec"
require "securerandom"
require "selenium-webdriver"

require_relative "../../lib/pages/command_center_page"
require_relative "../../lib/pages/login_page"
require_relative "../../lib/api/authorization"
require_relative "../../lib/devices/manager"
require_relative "../../lib/locations"
require_relative "../../lib/locations/location"
require_relative "../../lib/locations/location_manager"
require_relative "../../lib/pages/my_team_page"
require_relative "../../lib/api/user_manager"
