require "cucumber"
require "http"
require "rspec"
require "securerandom"
require "selenium-webdriver"

require_relative "../../command_center"
require_relative "../../login"
require_relative "../../lib/authorization"
require_relative "../../lib/devices/manager"
require_relative "../../lib/locations"
require_relative "../../lib/locations/location"
require_relative "../../lib/locations/location_manager"
require_relative "../../uitest"
require_relative "../../myteampage"
require_relative "../../user_manager"
